### ISSUE TITLE
Panic and access denied

### ISSUE THREAD

**Issue by guillaumeger** [kubecost/cost-model#63] opened 2019-04-30 15:59 UTC
```
I0430 15:53:35.143295       1 main.go:202] Starting cost-model (git commit "bd779830c98be5b101f2d9f0fe9b1e1f1fcea78f+dirty")
I0430 15:53:40.161470       1 main.go:219] Checked prometheus endpoint: http://monitoring-prometheus-server.monitoring
I0430 15:53:40.182421       1 provider.go:230] Found ProviderID starting with "aws", using AWS Provider
I0430 15:53:40.188758       1 awsprovider.go:306] starting download of "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json", which is quite large ...
I0430 15:53:40.303120       1 awsprovider.go:312] Finished downloading "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json"




I0430 15:54:05.585723       1 awsprovider.go:318] done loading "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json"
I0430 15:54:05.750668       1 awsprovider.go:415] Error downloading spot data AccessDenied: Access Denied
        status code: 403, request id: 45CA46E26DCA7F8B, host id: dETp2TmatqX+nh18l9/c74MMfbf2PD6IJmIXjaGdmuWw93iUA5Kw0IKua0cnSdg5x1fjPtG7KuM=
I0430 15:54:05.750751       1 main.go:158] Recording prices...
I0430 15:54:05.814567       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814591       1 costmodel.go:448] Node "ip-10-134-33-188.ec2.internal" RAM Cost := 0.001205
I0430 15:54:05.814602       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814610       1 costmodel.go:448] Node "ip-10-134-34-142.ec2.internal" RAM Cost := 0.004370
I0430 15:54:05.814619       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814633       1 costmodel.go:448] Node "ip-10-134-38-97.ec2.internal" RAM Cost := 0.004369
I0430 15:54:05.814644       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814655       1 costmodel.go:448] Node "ip-10-134-40-100.ec2.internal" RAM Cost := 0.001205
I0430 15:54:05.814665       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814675       1 costmodel.go:448] Node "ip-10-134-41-81.ec2.internal" RAM Cost := 0.004369
I0430 15:54:05.814684       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814695       1 costmodel.go:448] Node "ip-10-134-42-251.ec2.internal" RAM Cost := 0.004369
I0430 15:54:05.814704       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814712       1 costmodel.go:448] Node "ip-10-134-53-108.ec2.internal" RAM Cost := 0.004370
I0430 15:54:05.814724       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814734       1 costmodel.go:448] Node "ip-10-134-54-212.ec2.internal" RAM Cost := 0.001205
I0430 15:54:05.814746       1 costmodel.go:433] Use given nodeprice as whole node price
I0430 15:54:05.814757       1 costmodel.go:448] Node "ip-10-134-55-252.ec2.internal" RAM Cost := 0.004370
panic: interface conversion: interface {} is nil, not string

goroutine 97 [running]:
github.com/kubecost/cost-model/costmodel.getPVInfoVector(0x19e6260, 0xc0002ef8c0, 0xc000e4d740, 0x0, 0x0)
        /app/costmodel/costmodel.go:932 +0xa01
github.com/kubecost/cost-model/costmodel.ComputeCostData(0x2022660, 0xc000281940, 0x2090b00, 0xc0004ae000, 0x2072680, 0xc0004e7ba0, 0x1d0d36e, 0x2, 0xc00003ab60, 0xc000540dc0, ...)
        /app/costmodel/costmodel.go:139 +0x10f3
main.(*Accesses).recordPrices.func1(0xc000538e40)
        /app/main.go:159 +0x8c0
created by main.(*Accesses).recordPrices
        /app/main.go:156 +0x3f
```

**Comment by AjayTripathy** [comment] 2019-04-30 17:07
The Access Denied is expected if a key isn't supplied to read your spot data information, or the node you're running this on hasn't been provisioned with the correct permissions to look at s3 buckets. 

The panic is not expected-- looking into this.

**Comment by AjayTripathy** [comment] 2019-04-30 19:08
I just shipped #64 to hopefully stop the panics and come up with some sensible logs. If possible could you upgrade?

In the meantime, I know we have issues where default storageclass isn't set. Mind checking the storageclass on your PV's?

```kubectl get storageclass``` 

should return something like 

```gp2 (default)            kubernetes.io/aws-ebs   12d
```
If no (default) gets returned, that would be helpful information.

**Comment by guillaumeger** [comment] 2019-05-01 13:17
Thanks for the quick response!
Using version prod-1.18.3, I still have the same panic.
```
kubectl get storageclass:
NAME            PROVISIONER             AGE
default         kubernetes.io/aws-ebs   1y
gp2 (default)   kubernetes.io/aws-ebs   1y
```
We do have some pv/pvc where we specify an empty storageclass to avoid auto-provisioning of EBS volumes. I don't know if that can be a problem.

**Comment by AjayTripathy** [comment] 2019-05-01 22:55
Hi @guillaumeger , two things:

* Looks like master with the defensive programming upgrades to not panic in this situation did not make it to 1.18.3 .

* Yes, empty storageclass in the PVClaim was the issue. We will need to better support auto-provisioned EBS (#69) For now, though, #68 contains a workaround to allow you to use the cost-model minus support for manually provisioned PVs. I will update this bug when #68 makes it into production.

**Comment by guillaumeger** [comment] 2019-05-02 17:14
With version prod-1.19.1, it no longer panics. Thanks!

**Comment by AjayTripathy** [comment] 2019-05-02 17:29
#68 is in production and I've filed #69 to track the root cause, so closing for now. Let me know if I can help in any other way.

**Closed** 2019-05-02 17:29 UTC
