### ISSUE TITLE
Problem with cost frontend

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubecost/cost-model#774] opened 2021-04-19 22:33 UTC
I have my kubecost cost-model successfully running in my cluster:
```
kubectl get pods -n infra -lservice=kubecost
NAME                                 READY   STATUS    RESTARTS   AGE
kubecost-exporter-794f56fbb7-kdflw   1/1     Running   0          11m
```
kubecost is listening on port 9003:
```
kubectl exec -it kubecost-exporter-794f56fbb7-kdflw -n infra -- netstat -lptun
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::9003                 :::*                    LISTEN      1/app
```

following the instruction in the [README](https://github.com/kubecost/cost-model/blob/develop/ui/README.md)
i a shell i start the proxy:
```
kubect port-forward pod/kubecost-exporter-794f56fbb7-kdflw -n infra 9090:9003
```
in another shell i start the UI
```
cd ui
npm install
npx parcel src/index.html
```

When I navigate the UI at 127.0.0.1 the UI looks like:
<img width="1662" alt="Screen Shot 2021-04-19 at 3 27 25 PM" src="https://user-images.githubusercontent.com/51684360/115311125-f6b64600-a123-11eb-926e-400c0cb717c4.png">

the dev console show the following error (CORS error):
<img width="1418" alt="Screen Shot 2021-04-19 at 3 29 50 PM" src="https://user-images.githubusercontent.com/51684360/115311212-1c434f80-a124-11eb-8f80-866262463ac3.png">

If i try the curl by hand i receive a 404:
```
curl 'http://localhost:9090/model/allocation/compute?window=6d&aggregate=namespace&step=1d&accumulate=false'
404 page not found
```

**Comment by dwbrown2** [comment] 2021-04-19 22:38
@ltagliamonte-dd can you share how you installed kubecost?

cc @SheepGotoHeaven

**Comment by ltagliamonte-dd** [comment] 2021-04-19 23:52
I'm using my image to support a custom prom_label for cluster_id: ltagliamonte/kubecost-cost-model:dev
The pod doesn't log any error.
kubecost is running in a deployment with the following spec:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost-exporter
  labels:
    service: kubecost
    app: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kubecost
      app: exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9003"
      labels:
        service: kubecost
        app: exporter
    spec:
      serviceAccountName: kubecost-sa
      containers:
      - name: kubecost-exporter
        image: "ltagliamonte/kubecost-cost-model:dev"
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: kubecost-prom-secret
              key: TOKEN
        - name: PROMETHEUS_SERVER_ENDPOINT
          value: "https://<my_prom_endpoint>/data/metrics"
        - name: CLUSTER_ID
          value: "staging-us-west-2"
        - name: AWS_CLUSTER_ID
          value: "staging-us-west-2"
        - name: PROM_CLUSTER_ID_LABEL
          value: "k8s_cluster_id"
        - name: LOG_COLLECTION_ENABLED
          value: "false"
        - name: PRODUCT_ANALYTICS_ENABLED
          value: "false"
        - name: ERROR_REPORTING_ENABLED
          value: "false"
        - name: VALUES_REPORTING_ENABLED
          value: "false"
        - name: MAX_QUERY_CONCURRENCY
          value: "100"
        - name: KUBECOST_NAMESPACE
          value: {{ .Release.Namespace }}
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
```

**Comment by SheepGotoHeaven** [comment] 2021-04-20 16:26
Hi folks.

@ltagliamonte-dd are we sure the screenshot indicates a CORS error? I see headers that look like a CORS-based request is happening, but don't see indication of a CORS-related error.

The reason I ask is because I would not expect CORS to have any effect on `curl` results.

**Comment by ltagliamonte-dd** [comment] 2021-04-20 16:56
The chrome dev console says CORS:
<img width="1674" alt="Screen Shot 2021-04-20 at 9 48 36 AM" src="https://user-images.githubusercontent.com/51684360/115434545-abe90c80-a1bd-11eb-8670-a0eaab9ec650.png">

When i hoover the pointer on the error it says:
```
Cross-Origin Resource Sharing error: MissingAllowOriginHeader
```

I agree with you on the curl result, it shouldn’t return 404.
However:
```
curl "http://127.0.0.1:9090/costDataModel?timeWindow=7d&offset=7d"
{"code":200,"status":"success","data":{....
``` 

works with no problems.

**Comment by SheepGotoHeaven** [comment] 2021-04-20 21:48
I see. Thanks for the additional info! Seems like there may be an issue with that endpoint. I'll test it out and get back to you shortly

**Comment by SheepGotoHeaven** [comment] 2021-04-21 17:07
Hi @ltagliamonte-dd 

Thanks for bringing this to our attention. One part of the problem is that the URL the frontend tries to reach is incorrect -- it needs to be `/allocation/compute` rather than `/model/allocation/compute`.  I've opened a pull request to resolve that problem here: #775 

Unfortunately, with the URL correct I'm now getting a Prometheus query error resulting in the same failure to load data. So we're one step closer but not all the way there just yet.

**Comment by SheepGotoHeaven** [comment] 2021-04-21 22:14
It seems like we've figured out the rest, and in reality it's a combination of 3 things:

(1) The UI was pointing at the wrong URL

(2) If you launched the open source product in the same way I did (based on [this doc](https://github.com/kubecost/cost-model/blob/develop/kubecost-exporter.md)), you ran `kubectl apply -f https://raw.githubusercontent.com/kubecost/cost-model/develop/kubernetes/exporter/exporter.yaml --namespace cost-model`, but that yaml file has

```
env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "{{prometheusEndpoint}}"  #The endpoint should have the form http://<service-name>.<namespace-name>.svc
```

Which means it has to be modified to point at a running prometheus before application. You may have done this, but I didn't initially and it was an issue for me.

(3) Underneath it all, an honest-to-goodness CORS issue.

I'll issue another pull request tonight or tomorrow to address (2) and (3), and then ask you to try running again.

Thanks again!

**Comment by ltagliamonte-dd** [comment] 2021-04-21 22:23
Thank you!
Looking forward to test out the branch that fixes this issue.

**Comment by ltagliamonte-dd** [comment] 2021-04-26 15:30
Hello, any updates on this?

**Comment by SheepGotoHeaven** [comment] 2021-04-26 15:53
Hi 👋 , yes

Friday was busy with release preparations and I didn't finish then, but I haven't forgotten! I'm working on the last piece (CORS configuration now)

**Comment by SheepGotoHeaven** [comment] 2021-04-26 20:09
Thanks for your patience, @ltagliamonte-dd.

I have opened a pull request (#780) to address the CORS issue and other issues. If you want to check out the corresponding branch [neal/frontend-cors-issue](https://github.com/kubecost/cost-model/tree/neal/frontend-cors-issue) and see if this fixes things for you as well, that would be excellent 👍 

Please note that rather than running
```
kubectl apply -f https://raw.githubusercontent.com/kubecost/cost-model/develop/kubernetes/exporter/exporter.yaml
```

you will want to pull the file
```
https://raw.githubusercontent.com/kubecost/cost-model/neal/frontend-cors-issue/kubernetes/exporter/exporter.yaml
```

and edit it to replace
```
{{prometheusEndpoint}}
```

with a URI to your desired Prometheus instance, then subsequently run `kubectl apply -f` with the edited file.

**Comment by ltagliamonte-dd** [comment] 2021-04-27 19:44
Thanks @SheepGotoHeaven using your branch i don't see any CORS errors.
I'm still not able to get any data in it.. the backend seems to OOM with 10GB of RAM.
Will try to look into it.
Thanks!

**Comment by SheepGotoHeaven** [comment] 2021-04-28 15:28
I'm glad to hear that at least the original problem is solved 🙂 

I will close this ticket. Please don't hesitate to open another if the OOMing continues or you encounter other problems.

**Closed by SheepGotoHeaven** 2021-04-28 15:28 UTC
