### ISSUE TITLE
Prometheus end point exact pattern?

### ISSUE THREAD

**Issue by nandeeshb09** [kubecost/cost-model#19] opened 2019-04-10 16:57 UTC
Not able to give exact endpoint in deployment file,due to this ,pod is not starting can you help us on this.

what exactly we have to specify in value of endpoint.
    cpu: "10m"
              memory: "55M"
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: http://prometheus-prod-prometheus-server.pt-monitoring-prod.svc.cluster.local  #The endpoint should have the form http://<service-name>.<namespace-name>.svc.cluster.local 
          imagePullPolicy: Always

ERROR: ace is nil, prometheus is not running!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x163f10f]

**Comment by dwbrown2** [comment] 2019-04-10 18:00
Are you able to confirm that your prometheus server pod is named `prometheus-prod-prometheus-server` and successfully running in the `pt-monitoring-prod` namespace? 

Next question would be do you have the other required dependancies installed? Specifically, is Prometheus successfully scraping metrics from node exporter and kube-state-metrics?

Either way we should be producing a better error message here.

**Comment by dwbrown2** [comment] 2019-04-10 20:26
This appears to be panicking just after this log: https://github.com/kubecost/cost-model/blob/master/costmodel/costmodel.go#L578

Which would mean that the following query is failing for some reason. I suspect this has something to do with kube-state-metrics. Are you able to run this query directly in the Prometheus UI or let me know if there are any other steps for me to reproduce?

`(sum(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, storageclass) + on (persistentvolumeclaim) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace))`

**Comment by nandeeshb09** [comment] 2019-04-11 06:47
Below is the cost-model pod logs and this indicates that end point is working ,but pod is not able to create because of the below error.

Could you please help on this.?

2019/04/10 17:02:57 Checked prometheus endpoint: http://prometheus-prod-prometheus-server.pt-monitoring-prod.svc.cluster.local
done 
2019/04/10 17:03:12 Recording prices...
2019/04/10 17:03:12 Use given nodeprice as whole node price
2019/04/10 17:03:12 0.004265
2019/04/10 17:03:12 Use given nodeprice as whole node price
2019/04/10 17:03:12 0.004695
2019/04/10 17:03:12 Use given nodeprice as whole node price
2019/04/10 17:03:12 0.004041
2019/04/10 17:03:12 Use given nodeprice as whole node price
2019/04/10 17:03:12 0.004265
2019/04/10 17:03:12 Use given nodeprice as whole node price
2019/04/10 17:03:12 0.004265
2019/04/10 17:03:12 Interface map[data:map[result:[map[metric:map[namespace:activation-commons persistentvolumeclaim:chartmuseum-wtdcg-chartmuseum storageclass:standard] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:kube-system persistentvolumeclaim:anchore-demo-postgresql storageclass:standard] value:[1.55491579239e+09 25769803779]] map[metric:map[namespace:studio-dev persistentvolumeclaim:npm-verdaccio storageclass:standard-retain] value:[1.55491579239e+09 25769803779]] map[metric:map[namespace:devops-sonar-prod persistentvolumeclaim:sonar-data-sonarqube-0 storageclass:statefulset] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-config-orientdb-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 6442450947]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-dcm-amap-backend-container-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 16106127363]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-databases-orientdb-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-logs-amap-backend-container-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-tmp-amap-backend-container-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 322122547203]] map[metric:map[namespace:devops-sonar-prod persistentvolumeclaim:sonar-conf-ut-sonarqube-ut-0 storageclass:statefulset] value:[1.55491579239e+09 3221225475]] map[metric:map[namespace:pt-mongodb persistentvolumeclaim:datadir-mongodb-mongodb-replicaset-2 storageclass:standard] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:pt-monitoring-prod persistentvolumeclaim:prometheus-prod-prometheus-alertmanager storageclass:gp2] value:[1.55491579239e+09 6442450947]] map[metric:map[namespace:aiqx-dev persistentvolumeclaim:ebs-pvc-aiqx-server-dep-0 storageclass:standard] value:[1.55491579239e+09 64424509443]] map[metric:map[namespace:aiqx-dev persistentvolumeclaim:ebs-pvc-aiqx-ui-react-dep-0 storageclass:standard] value:[1.55491579239e+09 16106127363]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-pythonlib-amap-backend-container-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-rlib-amap-backend-container-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:devops-sonar-prod persistentvolumeclaim:sonar-data-ut-sonarqube-ut-0 storageclass:statefulset] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:pt-mongodb persistentvolumeclaim:datadir-mongodb-mongodb-replicaset-1 storageclass:standard] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:pt-monitoring-dev persistentvolumeclaim:prometheus-dev-prometheus-alertmanager storageclass:standard] value:[1.55491579239e+09 6442450947]] map[metric:map[namespace:pt-monitoring-dev persistentvolumeclaim:prometheus-dev-prometheus-server storageclass:standard] value:[1.55491579239e+09 322122547203]] map[metric:map[namespace:pt-monitoring-prod persistentvolumeclaim:prometheus-prod-prometheus-server storageclass:gp2] value:[1.55491579239e+09 1610612736003]] map[metric:map[namespace:sonar-vault persistentvolumeclaim:sonar-data-vault-sonarqube-vault-0 storageclass:statefulset] value:[1.55491579239e+09 3221225475]] map[metric:map[namespace:sonar-vault persistentvolumeclaim:sonar-extensions-vault-sonarqube-vault-0 storageclass:statefulset] value:[1.55491579239e+09 3221225475]] map[metric:map[namespace:devops-sonar-prod persistentvolumeclaim:sonar-conf-sonarqube-0 storageclass:statefulset] value:[1.55491579239e+09 3221225475]] map[metric:map[namespace:devops-sonar-prod persistentvolumeclaim:sonar-extensions-sonarqube-0 storageclass:statefulset] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-chronicle-amap-backend-container-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 16106127363]] map[metric:map[namespace:amap-qa persistentvolumeclaim:pvc-qa-logs-amap-rest-qa-0 storageclass:standard-retain] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:devops-jetbrains-prod persistentvolumeclaim:jls-pvc-jls-0 storageclass:statefulset] value:[1.55491579239e+09 3221225475]] map[metric:map[namespace:devops-sonar-prod persistentvolumeclaim:sonar-extensions-ut-sonarqube-ut-0 storageclass:statefulset] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:pt-mongodb persistentvolumeclaim:datadir-mongodb-mongodb-replicaset-0 storageclass:standard] value:[1.55491579239e+09 32212254723]] map[metric:map[namespace:pt-redis persistentvolumeclaim:redis-data-redis-master-0 storageclass:standard] value:[1.55491579239e+09 25769803779]]] resultType:vector] status:success]. If the interface is nil, prometheus is not running!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x163f10f]

goroutine 127 [running]:
main.(*Accesses).recordPrices.func1(0xc0003843c0)
	/app/main.go:105 +0xcf
created by main.(*Accesses).recordPrices
	/app/main.go:95 +0x3f

**Comment by nandeeshb09** [comment] 2019-04-11 06:48
> Are you able to confirm that your prometheus server pod is named `prometheus-prod-prometheus-server` and successfully running in the `pt-monitoring-prod` namespace?
> 
> Next question would be do you have the other required dependancies installed? Specifically, is Prometheus successfully scraping metrics from node exporter and kube-state-metrics?
> 
> Either way we should be producing a better error message here.
Are you able to confirm that your prometheus server pod is named `prometheus-prod-prometheus-server` and successfully running in the `pt-monitoring-prod` namespace?
>  Yes its working .

**Comment by nandeeshb09** [comment] 2019-04-11 07:00
> This appears to be panicking just after this log: https://github.com/kubecost/cost-model/blob/master/costmodel/costmodel.go#L578
> 
> Which would mean that the following query is failing for some reason. I suspect this has something to do with kube-state-metrics. Are you able to run this query directly in the Prometheus UI or let me know if there are any other steps for me to reproduce?
> 
> `(sum(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, storageclass) + on (persistentvolumeclaim) group_right(storageclass) sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim, namespace))`

Yes i am able to run this query  from Prometheus UI.

**Comment by nandeeshb09** [comment] 2019-04-11 07:26
Hi Guys,

Its working and pod is up n running fine.
But if I hit this url http://localhost:9003/costDataModel?timeWindow=1d its showing the output ,but its coming as text output not as proper UI.
is there other way to get the proper UI?

**Comment by luisdavim** [comment] 2019-04-11 14:43
I think that is expected, as far as I understand the UI is not open source, only the API

**Comment by dwbrown2** [comment] 2019-04-11 19:04
Glad you were able to get past this issue -- thanks again for helping us find it. @luisdavim is right -- to start we've just open sourced the cost model itself. You can access the dashboard UI and the full Kubecost product (free for small clusters and for evaluation) at http://kubecost.com/install. Let me know if you have any questions.

**Comment by dwbrown2** [comment] 2019-04-11 21:48
I'll plan to close this, because it sounds like this particular issue was resolved. Feel free to open another issue for further discussion though.

**Comment by nandeeshb09** [comment] 2019-04-12 05:07
Sure @dwbrown2 You can close this issue.
Thanks guys for your help.

**Comment by dwbrown2** [comment] 2019-04-12 05:13
You're welcome @nandeeshb09. Let me know if you think we can clarify anything in our documentation  around this or if we can help with anything else!

**Closed by dwbrown2** 2019-04-12 05:13 UTC

**Comment by nandeeshb09** [comment] 2019-04-12 06:00
@dwbrown2 Is it possible to give Prometheus queries? so that i can run these directly on Prometheus server to get cost of each resources.?

**Comment by dwbrown2** [comment] 2019-04-12 15:19
@nandeeshb09 this is somewhat complex because you are joining multiple sets of data (usage/requests from prometheus) and pricing data (from your cloud provider). You can join these in Prometheus by having it scape the `/mertrics` endpoint exposed by this project. 

Here are the usage queries though: 
https://github.com/kubecost/cost-model/blob/master/costmodel/costmodel.go#L67

Is there something specific you are trying to accomplish? Happy to give more specific guidance.

**Comment by nandeeshb09** [comment] 2019-04-15 13:03
Sure Thank you

**Comment by nandeeshb09** [comment] 2019-04-16 13:02
https://github.com/kubecost/cost-model/blob/master/costmodel/costmodel.go#L67 these are not working..

@dwbrown2 can you give me the queries which are related to only cost level.?

**Comment by dwbrown2** [comment] 2019-04-16 15:55
Hi @nandeeshb09, the cost data can be ingested into Prometheus via this project's `/metrics` endpoint. You just need to have your Prometheus scrape this endpoint and then you can write queries against `node_ram_hourly_cost`, `node_cpu_hourly_cost`, and `node_total_hourly_cost`. Does that help? Let me know if we can help you set this up, if you have further questions, or if you want additional metrics included!

**Comment by nandeeshb09** [comment] 2019-04-17 04:59
the cost data can be ingested into Prometheus via this project's /metrics endpoint.-- I did this already.
Thank u.

**Comment by dwbrown2** [comment] 2019-04-17 05:41
@nandeeshb09, @AjayTripathy just added new data to the /metrics endpoint. I also created this new documentation: https://github.com/kubecost/cost-model/blob/master/PROMETHEUS.md

Is this helpful for you?

**Comment by dwbrown2** [comment] 2019-04-24 16:33
@nandeeshb09 anything else we can get you here?
