### ISSUE TITLE
Deprecated kube-state-metrics metrics

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-model#804] opened 2021-05-17 15:54 UTC
According to kube-state-metrics [documentation](https://kubernetes.io/blog/2021/04/13/kube-state-metrics-v-2-0/#what-is-new-in-v2-0) and [repo](https://github.com/kubernetes/kube-state-metrics/tree/release-1.9/docs#metrics-deprecation) the metric `kube_pod_container_resource_requests_memory_bytes` is deprecated and removed from version v2.0 of kube-state-metrics.

Since [May 15th](https://github.com/prometheus-community/helm-charts/releases/tag/prometheus-14.0.0) the Prometheus chart uses version v2.0 of kube-state-metrics.

So for those who have a separate installation of Prometheus the integration no longer works if they update to the latest version of the Prometheus chart.

<img width="1166" alt="Screenshot 2021-05-17 at 17 38 55" src="https://user-images.githubusercontent.com/36044817/118518411-6413c180-b738-11eb-8052-8ab7f9a4aa22.png">

It may be time to ditch all the deprecated metrics, both those of kube-state-metrics and those of [cadvisor](https://github.com/kubecost/cost-analyzer-helm-chart/issues/747). 

It is time to move on! ❤️ 🚀

**Comment by pierluigilenoci** [comment] 2021-05-19 09:00
@dwbrown2 could you please take a look?

**Comment by dwbrown2** [comment] 2021-05-19 16:08
@pierluigilenoci this is a duplicate of https://github.com/kubecost/docs/issues/74

**Closed by dwbrown2** 2021-05-19 16:08 UTC

**Comment by pierluigilenoci** [comment] 2021-05-19 17:24
Ok thanks, but mine was more liked and in the right repo. :P
