### ISSUE TITLE
Inexplicable numbers in the saving panel 

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-model#880] opened 2021-07-28 11:55 UTC
The numbers shown inside the "Saving - Request Sizing Recommendations" page makes no sense to me.

We have configured the page this way:

<img width="598" alt="Screenshot 2021-07-28 at 13 32 20" src="https://user-images.githubusercontent.com/36044817/127316141-ea636482-758f-40a9-8c11-ccbcfc55798d.png">

These lines appear in the "Breakdown" list:

<img width="1318" alt="Screenshot 2021-07-28 at 13 31 27" src="https://user-images.githubusercontent.com/36044817/127316291-3c8d1a38-2e27-463e-ba22-c92e67caef76.png">

The "* request" and "* recomm'd" columns have exactly the same value.

Why are these pods shown?
Why are these pods considered "underprovisioned"?
How is efficiency calculated?

**Comment by pierluigilenoci** [comment] 2021-07-28 12:26
Could it be connected to #793?

**Comment by pierluigilenoci** [comment] 2021-07-29 09:09
Today another report attracted my attention, always in the "Saving - Request Sizing Recommendations" tab.

<img width="1109" alt="Screenshot 2021-07-29 at 11 05 38" src="https://user-images.githubusercontent.com/36044817/127464528-b48a573e-58ac-452a-a867-018d40bd958c.png">

Here the recommended values are lower than the current request but the pods are still reported "underprovisioned".

Why?
Is there something I didn't understand?

**Comment by pierluigilenoci** [comment] 2021-07-29 10:20
@AjayTripathy could you please take a look?

**Comment by nikovacevic** [comment] 2021-08-03 22:09
Hi @pierluigilenoci. It is possible that, if you open the details dialog for one of those rows, one of the individual pods within the deployment may have been under-provisioned. If that is not the case, then we'll have to investigate more thoroughly.

We're also planning to make some improvements to this API in the near future to clear up some ongoing confusion about what certain numbers mean. When that effort begins, we'll update you via this issue.

**Comment by pierluigilenoci** [comment] 2021-08-09 09:31
@nikovacevic the cpu/memory values shown are the maximum cpu and memory values across all pods in the deployment. So there can't be any pod that uses more cpu/memory than the values shown. How then can they be underprovisioned?

**Comment by pierluigilenoci** [comment] 2021-08-09 09:33
@nikovacevic I suggest making it possible for the user to be able to hide pods that do not need configuration from the report, leaving only the ones to focus attention on.

**Comment by dwbrown2** [comment] 2021-08-19 00:16
@nikovacevic were you able to reproduce? I unfortunately haven't been able to yet.

**Comment by pierluigilenoci** [comment] 2021-08-19 10:52
Keep seeing the problem. 

<img width="1491" alt="Screenshot 2021-08-19 at 12 44 35" src="https://user-images.githubusercontent.com/36044817/130056492-35083e7e-8f6c-4589-9b2b-430b154a6e4c.png">

For me, the simplest solution to recreate it is to run a simple empty container that does nothing on a cluster and adapt the requests to Kubecost's suggestions.

**Comment by nikovacevic** [comment] 2021-08-19 14:49
I have not been able to reproduce yet, but I can try @pierluigilenoci's suggestion.

**Comment by pierluigilenoci** [comment] 2021-09-01 11:49
@nikovacevic any update?

**Comment by nikovacevic** [comment] 2021-09-01 16:31
No update yet, @pierluigilenoci

**Comment by pierluigilenoci** [comment] 2021-09-15 12:48
@nikovacevic since I opened the ticket many cost-analyzer versions have been released so I thought I'd check again. Unfortunately, the problem always exists. 😞 

<img width="1406" alt="Screenshot 2021-09-15 at 14 28 07" src="https://user-images.githubusercontent.com/36044817/133436186-1b9e2e5d-7411-4081-a307-314b7486fac9.png">

**Comment by pierluigilenoci** [comment] 2021-11-24 10:47
@dwbrown2 @nikovacevic any update on this?

**Comment by dwbrown2** [comment] 2021-11-24 20:51
Our team has still be unable to reproduce this, @pierluigilenoci. Is there any more context you can share? Does this happen in many workloads? Are there common traits for those it does happen with?

**Comment by pierluigilenoci** [comment] 2021-12-02 09:51
@dwbrown2 did @nikovacevic do as I suggested here? https://github.com/kubecost/cost-model/issues/880#issuecomment-901813476

**Comment by nikovacevic** [comment] 2021-12-03 23:37
@pierluigilenoci I have not, but you will be the first to know when someone on the team is able to get to your request.

**Comment by pierluigilenoci** [comment] 2022-01-05 10:47
@nikovacevic have you tried to replicate the issue with my suggestion?

**Comment by kbrwn** [comment] 2022-01-05 17:21
@pierluigilenoci It seems likely that this issue is specific to your cluster and may be the result of incomplete resource utilization data coming from ksm, cadvisor, or possibly the k8s api. It would be preferable to debug this issue via a support ticket rather than a github issue so that we can share information privately and discuss specifics of your cluster. Could you fetch a bug report from /settings.html and then email support@kubecost.com with a reference to this issue? Thanks!

**Comment by kbrwn** [comment] 2022-02-08 19:30
@pierluigilenoci Are you interested in debugging this issue further via a support ticket?

**Comment by kbrwn** [comment] 2022-02-10 23:02
@pierluigilenoci I am going to close this issue out. Please feel free to email support@kubecost.com if you would like to follow up. We would be happy to look into your cluster data specifically. 

Furthermore our most recent release [v1.90.1](https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.90.1)  has some code to improve consistency across the application.

**Closed by kbrwn** 2022-02-10 23:02 UTC
