### ISSUE TITLE
Support static list in "Available Clusters" view

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-model#812] opened 2021-05-26 16:42 UTC
In multi/switch cluster the initial select available cluster view should be a static list, always in the same order, rather than a dynamic list as it is now.

**Comment by AjayTripathy** [comment] 2021-05-26 17:20
Duplicate of https://github.com/kubecost/cost-analyzer-helm-chart/issues/916 ?

**Closed** 2021-05-26 18:36 UTC
